### ISSUE TITLE
Error code 202

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#499] opened 2021-12-06 15:00 UTC
No clue what this doesn't like as both csvs look fine in Notepad+, but on testing the site practically **all** children in my Header file are now returning unmatched `<SEX>` compared with the previous year file.

![image](https://user-images.githubusercontent.com/89449804/144868347-7f4510e0-4ac9-460f-9408-b52c8d215e4b.png)

**Comment by dezog** [comment] 2021-12-14 14:16
Hi @SLornieCYC, I've had no luck recreating this behaviour with synthetic data, so all I have is hunches - would you be able to confirm:
- the error is appearing for identical entries (no sneaky spaces/tabs in the file?)
- are there any duplicated CHILD ID's in either file? (as currently implemented, this may throw off the indexing)


I've just changed the only thing I could spot that might be causing issues, the line `error_locations = header.index[error_mask]`, to `error_locations = header_merged.index[error_mask]`, as the mask is created based on header_merged - it's possible they're sorted differently or something. 

I'll let you know when the changes go live and you can test whether the issue is still happening, hopefully that does it 🤞

**Comment by SLornieCYC** [comment] 2021-12-23 12:05
Hi @dezog afraid my dataset is still failing this error after the latest corrections (which I think should include the change you mention above as can see other fixes have gone live).

In terms of your questions:

- Entries appear identical in Notepad+ with no spaces around or between values (both csvs are direct exports from the DFE portal last year so any formatting issues _should_ be common to both files anyway)
- No duplicated child IDs in either file (and rule 208 - which has similar logic and still uses `error_locations = header.index[error_mask]` - only returns a handful of errors which all appear legitimate).

![image](https://user-images.githubusercontent.com/89449804/147237815-cf43293c-49b3-46a1-afa1-5cd29fd228e9.png)

**Comment by tab1tha** [comment] 2021-12-23 16:46
Hi @SLornieCYC I noticed that the spelling of the first header file in your screenshot starts with a capital H and the other starts with a small h. Is that normal?

That could mean that 'Header' will be found but 'Header_last' will not be found. Since 'header_last' will be formed instead.

**Comment by SLornieCYC** [comment] 2022-01-06 09:49
Hi @tab1tha I can try with the file names being the same case but I don't think that should matter - when csvs are loaded in the table names are set (in python) based on the columns within the loaded file rather than the name of the file itself (per ingress.py and config.py).  I think if the loaded file name was a problem I would have all of the Header>Header_last errors flagged (`<DOB>`, `<ETHNIC>`, `<UPN>` etc) and not only `<SEX>`.

**Comment by tab1tha** [comment] 2022-01-07 06:08
That is true. You have a point there.

**Comment by dezog** [comment] 2022-01-28 11:40
As mentioned in the thread on https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/517, this might be down to one year's gender code column containing missing values, which will lead to them all being stored as floats in the dataframe so `.astype(str)` gives `'1.0'` or `'2.0'` (or `'nan'`), instead of  `'1'` or `'2'`

I think it's worth getting a fix in asap for this one as it ends up affecting every child and is quite prominently wrong! 

But this issue will potentially affect any rules comparing integer values so we should also think about a general fix in the not-too-long term

**Comment by dezog** [comment] 2022-02-07 17:03
finally fixed by https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/532

**Closed as completed by dezog** 2022-02-07 17:03 UTC
Labels: bug
